const $=id=>document.getElementById(id);
let selected=null,available=false,busy=false,current=null,pollTimer=null;
const statusNames={queued:'Waiting to start',running:'Analyzing your app',completed:'Analysis complete',partial:'Some checks could not finish',failed:'Analysis could not finish',unavailable:'Unavailable',not_needed:'Not needed'};
async function api(path,options){const response=await fetch(path,options);let data;try{data=await response.json()}catch{throw Error('The server returned an unexpected response.')}if(!response.ok)throw Error(data.error||'Unable to complete this request.');return data;}
function selectFile(file){$('message').textContent='';selected=null;if(!file)return;if(!file.name.toLowerCase().endsWith('.apk')){$('message').textContent='Please choose an APK file.';return;}if(!file.size||file.size>64*1024*1024){$('message').textContent='Choose an APK under 64 MB.';return;}selected=file;$('file-name').textContent=file.name;$('file-size').textContent=(file.size/1024/1024).toFixed(1)+' MB';$('analyze').disabled=!available||busy;}
async function health(){try{const state=await api('/api/health');available=state.connected&&state.ready;$('connection').textContent=available?'Ready for your app.':state.connected?'The analysis service is connected, but some tools are not ready yet.':'The analysis server is not connected yet. Uploads will become available when it is ready.';$('connection').classList.toggle('ready',available);$('apk').disabled=!available||busy;$('analyze').disabled=!available||!selected||busy;return state;}catch{$('connection').textContent='Unable to check availability. Please try again later.';return {connected:false,ready:false};}}
$('apk').addEventListener('change',e=>selectFile(e.target.files[0]));
for(const type of ['dragenter','dragover'])$('drop').addEventListener(type,e=>{e.preventDefault();if(available&&!busy)$('drop').classList.add('over');});
for(const type of ['dragleave','drop'])$('drop').addEventListener(type,e=>{e.preventDefault();$('drop').classList.remove('over');if(type==='drop'&&available&&!busy)selectFile(e.dataTransfer.files[0]);});
function renderJob(job){current=job;$('job').hidden=false;$('job-status').textContent=statusNames[job.status]||job.status;$('percent').textContent=(job.progress||0)+'%';$('progress').value=job.progress||0;$('steps').replaceChildren();for(const tool of job.tools||[]){const row=document.createElement('div');row.className='step';const label=document.createElement('span');label.textContent=tool.name;const status=document.createElement('small');status.textContent=statusNames[tool.status]||tool.status;row.append(label,status);$('steps').append(row);if(tool.detail){const detail=document.createElement('p');detail.textContent=tool.detail;detail.className='message';$('steps').append(detail);}}if(['completed','partial','failed'].includes(job.status)){busy=false;$('analyze').disabled=!available||!selected;$('apk').disabled=!available;$('analyze').textContent='Analyze another app';if(job.detail)$('message').textContent=job.detail;if(job.report){$('download').href='/api/jobs/'+job.id+'/download';$('download').hidden=false;$('report-download').hidden=false;$('summary').replaceChildren();const info=document.createElement('p');info.textContent=`${job.report.inventory.files} files · ${job.report.inventory.native_libraries.length} native libraries`;const limit=document.createElement('p');limit.textContent=job.report.limitations;$('summary').append(info,limit);}}}
async function poll(id){try{const job=await api('/api/jobs/'+id);renderJob(job);if(['queued','running'].includes(job.status))pollTimer=setTimeout(()=>poll(id),2500);}catch(e){$('message').textContent=e.message;busy=false;$('analyze').disabled=!available||!selected;$('apk').disabled=!available;}}
async function startAnalysis(){if(!available||!selected||busy)throw Error('Choose an APK when analysis is ready.');busy=true;clearTimeout(pollTimer);$('analyze').disabled=true;$('apk').disabled=true;$('download').hidden=true;$('report-download').hidden=true;$('summary').replaceChildren();$('message').textContent='';$('job').hidden=false;$('steps').replaceChildren();$('job-status').textContent='Uploading your app';$('progress').value=0;$('percent').textContent='0%';try{const job=await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/jobs');xhr.setRequestHeader('x-file-name',encodeURIComponent(selected.name));xhr.setRequestHeader('x-upload-size',String(selected.size));xhr.upload.onprogress=e=>{if(e.lengthComputable){const value=Math.round(e.loaded/e.total*100);$('progress').value=value;$('percent').textContent=value+'%';}};xhr.onerror=()=>reject(Error('The upload was interrupted. Try again.'));xhr.onload=()=>{try{const data=JSON.parse(xhr.responseText);if(xhr.status!==202)return reject(Error(data.error||'The upload could not finish.'));resolve(data);}catch{reject(Error('The server returned an unexpected response.'));}};xhr.send(selected);});current={id:job.id};await poll(job.id);return {id:job.id};}catch(e){busy=false;$('message').textContent=e.message;$('analyze').disabled=!available||!selected;$('apk').disabled=!available;$('job-status').textContent='Upload could not finish';throw e;}}
$('analyze').addEventListener('click',()=>startAnalysis().catch(()=>{}));
$('report-download').addEventListener('click',()=>{if(!current?.report)return;const blob=new Blob([JSON.stringify(current.report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='the-break-down-summary.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
if(document.modelContext?.registerTool){for(const tool of [{name:'read_analysis_status',description:'Read the current app analysis and server availability.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(Object.keys(input||{}).length)throw Error('No arguments expected.');return {server:await health(),job:current};}},{name:'start_selected_apk_analysis',description:'Upload and analyze the APK already selected in the visible interface.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(Object.keys(input||{}).length)throw Error('No arguments expected.');return startAnalysis();}}])Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}
health();setInterval(()=>{if(!busy)health();},30000);
