"""Automatic static analysis; no uploaded application code is executed."""
import hashlib
import json
import os
import re
import signal
import subprocess
import urllib.request
import uuid
import zipfile
from pathlib import Path

MAX_UPLOAD = 250 * 1024 * 1024
MAX_EXPANDED = 1024 * 1024 * 1024
TOOLS = ('MobSF', 'Apktool', 'Ghidra', 'Blutter', 'hermes-dec')

def inspect_apk(path):
    with zipfile.ZipFile(path) as archive:
        entries = archive.infolist()
        if len(entries) > 50000 or sum(e.file_size for e in entries) > MAX_EXPANDED:
            raise ValueError('The app exceeds the analysis size limit.')
        names = {e.filename for e in entries}
        if 'AndroidManifest.xml' not in names:
            raise ValueError('This ZIP file does not contain an Android app manifest.')
        libs = sorted(n for n in names if re.fullmatch(r'lib/(arm64-v8a|armeabi-v7a|x86|x86_64)/[^/]+\.so', n))
        flutter = {'lib/arm64-v8a/libapp.so', 'lib/arm64-v8a/libflutter.so'} <= names
        hermes = []
        for entry in entries:
            if entry.filename.startswith('assets/') and entry.file_size >= 8:
                with archive.open(entry) as f:
                    if f.read(8) == bytes.fromhex('c61fbc03c103191f'):
                        hermes.append(entry.filename)
        return {'files': len(entries), 'native_libraries': libs, 'flutter_arm64': flutter,
                'hermes_bundles': hermes, 'has_dex': any(re.fullmatch(r'classes\d*\.dex', n) for n in names)}

def run_process(args, log, timeout=600):
    """Bound a whole process group, including compiler/decompiler children."""
    with open(log, 'wb') as output:
        proc = subprocess.Popen(args, stdout=output, stderr=subprocess.STDOUT, start_new_session=True)
        try:
            code = proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            os.killpg(proc.pid, signal.SIGKILL)
            proc.wait()
            raise RuntimeError('The analysis time limit was reached.')
    if code:
        raise RuntimeError(f'Tool exited with code {code}. See its log in the download.')

def extract_member(apk, name, destination):
    # Destination is generated by the service, never taken from the ZIP path.
    with zipfile.ZipFile(apk) as archive, archive.open(name) as source, open(destination, 'wb') as output:
        while chunk := source.read(1024 * 1024):
            output.write(chunk)

def mobsf(apk, out):
    base, key = os.environ.get('MOBSF_URL'), os.environ.get('MOBSF_API_KEY')
    if not base or not key:
        raise FileNotFoundError('MobSF is not connected.')
    def call(route, data, content_type='application/x-www-form-urlencoded'):
        req = urllib.request.Request(base.rstrip('/') + '/api/v1/' + route, data=data,
                                     headers={'Authorization': key, 'Content-Type': content_type})
        with urllib.request.urlopen(req, timeout=600) as response:
            return json.load(response)
    import urllib.parse
    boundary = 'breakdown' + uuid.uuid4().hex
    body = (f'--{boundary}\r\nContent-Disposition: form-data; name="file"; filename="app.apk"\r\n'
            'Content-Type: application/vnd.android.package-archive\r\n\r\n').encode()
    body += apk.read_bytes() + f'\r\n--{boundary}--\r\n'.encode()
    uploaded = call('upload', body, 'multipart/form-data; boundary=' + boundary)
    if uploaded.get('scan_type') != 'apk' or not uploaded.get('hash'):
        raise RuntimeError('MobSF did not accept the APK.')
    form = urllib.parse.urlencode({'hash': uploaded['hash']}).encode()
    try:
        scan = call('scan', form)
        if scan.get('error'):
            raise RuntimeError('MobSF could not analyze this app.')
        report = call('report_json', form)
        (out / 'mobsf.json').write_text(json.dumps(report, indent=2))
    finally:
        deleted = call('delete_scan', form)
        if deleted.get('error'):
            raise RuntimeError('MobSF could not remove its uploaded app copy.')

def analyze(apk, directory, update):
    out = directory / 'results'
    out.mkdir(exist_ok=True)
    facts = inspect_apk(apk)
    report = {'filename': 'app.apk', 'sha256': hashlib.sha256(apk.read_bytes()).hexdigest(),
              'inventory': facts, 'tools': [], 'limitations': 'Static analysis cannot recover the original project or verify runtime behavior.'}
    steps = [('MobSF', True), ('Apktool', True), ('Ghidra', bool(facts['native_libraries'])),
             ('Blutter', facts['flutter_arm64']), ('hermes-dec', bool(facts['hermes_bundles']))]
    for index, (tool, applicable) in enumerate(steps):
        row = {'name': tool, 'status': 'running' if applicable else 'not_needed'}
        report['tools'].append(row)
        update(tool=tool, progress=round(index / len(steps) * 100), tools=report['tools'])
        if not applicable:
            continue
        target = out / tool
        target.mkdir(exist_ok=True)
        try:
            if tool == 'MobSF':
                mobsf(apk, target)
            elif tool == 'Apktool':
                jar = Path(os.environ.get('APKTOOL_JAR', '/opt/tools/apktool.jar'))
                if not jar.is_file(): raise FileNotFoundError('Apktool is not installed.')
                run_process(['java', '-Xmx1536m', '-jar', str(jar), 'd', str(apk), '-o', str(target / 'decoded')], target / 'tool.log')
                if not (target / 'decoded' / 'apktool.yml').is_file(): raise RuntimeError('Apktool did not create decoded output.')
            elif tool == 'Ghidra':
                launcher = Path(os.environ.get('GHIDRA_HEADLESS', '/opt/tools/ghidra/support/analyzeHeadless'))
                if not launcher.is_file(): raise FileNotFoundError('Ghidra is not installed.')
                libraries = facts['native_libraries'][:12]
                row['library_limit'] = 12
                row['libraries_not_analyzed'] = len(facts['native_libraries']) - len(libraries)
                for num, library in enumerate(libraries):
                    native = target / f'library-{num}.so'
                    extract_member(apk, library, native)
                    projects = target / 'projects'
                    projects.mkdir(exist_ok=True)
                    run_process([str(launcher), str(projects), f'native-{num}', '-import', str(native),
                                 '-analysisTimeoutPerFile', '180', '-max-cpu', '2', '-scriptPath', '/app/service',
                                 '-postScript', 'ExportNative.java', str(target / f'library-{num}.c'), '-deleteProject'], target / f'library-{num}.log', 240)
                    if not (target / f'library-{num}.c').is_file(): raise RuntimeError('Ghidra did not export native analysis.')
            elif tool == 'Blutter':
                script = Path(os.environ.get('BLUTTER_SCRIPT', '/opt/tools/blutter/blutter.py'))
                if not script.is_file(): raise FileNotFoundError('Blutter is not installed.')
                run_process(['python3', str(script), str(apk), str(target / 'flutter')], target / 'tool.log', 1800)
                if not (target / 'flutter' / 'pp.txt').is_file(): raise RuntimeError('Blutter did not produce an object dump.')
            else:
                import shutil
                command = shutil.which('hbc-decompiler')
                if not command: raise FileNotFoundError('Hermes decompiler is not installed.')
                for num, bundle in enumerate(facts['hermes_bundles'][:8]):
                    native = target / f'bundle-{num}.hbc'
                    extract_member(apk, bundle, native)
                    dest = target / f'bundle-{num}.txt'
                    run_process([command, str(native), str(dest)], target / f'bundle-{num}.log')
                    if not dest.is_file() or not dest.stat().st_size: raise RuntimeError('Hermes produced no decompiled output.')
                row['bundles_not_analyzed'] = max(0, len(facts['hermes_bundles']) - 8)
            row['status'] = 'completed'
        except FileNotFoundError as error:
            row.update(status='unavailable', detail=str(error))
        except Exception as error:
            row.update(status='failed', detail=str(error)[:300])
        update(tools=report['tools'])
    (out / 'report.json').write_text(json.dumps(report, indent=2))
    with zipfile.ZipFile(directory / 'results.zip', 'w', zipfile.ZIP_DEFLATED) as archive:
        for file in out.rglob('*'):
            if file.is_file(): archive.write(file, file.relative_to(out))
    complete = all(r['status'] in ('completed', 'not_needed') for r in report['tools'])
    update(status='completed' if complete else 'partial', progress=100, report=report, tool=None)
    apk.unlink(missing_ok=True)
    return report
